### ISSUE TITLE
Add support for Connector type applications

### ISSUE THREAD

**Issue by caspereijkens** [Axual/terraform-provider-axual#1]
For our usecase the Axual Provider must support Connector type applications.

**Comment by caspereijkens** [comment]
@kasparAxual Thanks for the work you have done to improve this product. When do you expect to support connectors? That is the last one on our list to start using this it :)

**Comment by caspereijkens** [comment]
Ok, thanks for letting us know.

**Comment by kasparAxual** [comment]
If there are any other questions regarding connector applications, please let us know or open a new issue. Closing this issue.
