### ISSUE TITLE
Add support for AVRO key type and AVRO value type

### ISSUE THREAD

**Issue by caspereijkens** [Axual/terraform-provider-axual#2]
For our usecase the Axual Provider must support AVRO key type and AVRO value type for streams.

**Comment by caspereijkens** [comment]
Is AVRO key type and value type supported with 2.0? @kasparAxual

**Comment by kasparAxual** [comment]
Hey @caspereijkens Yes, Avro key type and value type are supported with Axual Terraform Provider from v2.0.

- Kindly find the Schema version resource example here: https://registry.terraform.io/providers/Axual/axual/latest/docs/resources/schema_version
- Here is how to refer to it from a topic(=stream): https://registry.terraform.io/providers/Axual/axual/latest/docs/resources/topic
- Here is how to refer to it from a topic(=stream) configuration: https://registry.terraform.io/providers/Axual/axual/latest/docs/resources/topic_config
- Here is full example of everything working together, please look for "axual_schema_version": https://registry.terraform.io/providers/Axual/axual/latest/docs-
