### ISSUE TITLE
When migrating from 1.1.3 to 2.1.0, streams and topics clash

### ISSUE THREAD

**Issue by caspereijkens** [Axual/terraform-provider-axual#30]
When migrating from v1.1.3 to v2.1.0, streams must be renamed to topics. However, when doing `terraform init -upgrade` and then re-applying, I get
```
Error: no schema available for module.streams_shared.axual_stream.axual_streams["stream_1"] while reading state; this is a bug in Terraform and should be reported
```

**Comment by DarioAxual** [comment]
Hello @caspereijkens,

Sorry for the late reply, have you followed the procedure for upgrading to >=2.0.0 documentation https://github.com/Axual/terraform-provider-axual/tree/master?tab=readme-ov-file#upgrading-to-version-200 that shows a script to rename terraform resources to the new names?

This is the script described there https://github.com/Axual/terraform-provider-axual/blob/master/upgrade/upgrade-2.sh

**Comment by caspereijkens** [comment]
I had not seen this resource yet, thanks for sharing it.

**Comment by kasparAxual** [comment]
If there are any other questions please let us know or open a new issue. Closing this issue.
