### ISSUE TITLE
Deleting a Public environment surprisingly worked, but recreating fails

### ISSUE THREAD

**Issue by caspereijkens** [Axual/terraform-provider-axual#31]
I somehow managed to delete a public environment by removing it from the TF config. It is also gone from the `tf state`. But then I failed to recreate it. It looks a lot like the bug that happens when deleting a TF-managed object from the UI.

I read that the UI bug is already under investigation but since this is slightly different I wanted to share it to help your investigation.

```
module.environments_tst.axual_environment.integration: Creating...
╷
│ Error: CREATE request error for environment resource
│ 
│   with module.environments_tst.axual_environment.integration,
│   on ../../modules/environments/main.tf line 27, in resource "axual_environment" "integration":
│   27: resource "axual_environment" "integration" {
│ 
│ Error message: status: 500, body: {
│   "status" : "INTERNAL_SERVER_ERROR",
│   "message" : "{\"successful\":false,\"errorMessage\":\"Received fatal alert: internal_error; nested exception is javax.net.ssl.SSLException: Received fatal alert: internal_error\",\"body\":null,\"error\":true}",
│   "errors" : [ "500 : \"{\"successful\":false,\"errorMessage\":\"Received fatal alert: internal_error; nested exception is javax.net.ssl.SSLException: Received fatal alert: internal_error\",\"body\":null,\"error\":true}\"" ],
│   "subErrors" : null
│ }
```

**Comment by kasparAxual** [comment]
Thank you for the report. We have scheduled this bufix in April 2024.

**Comment by kasparAxual** [comment]
Hey I tested and this issue has now been resolved. I tested with a public `axual_environment` in this guide: https://registry.terraform.io/providers/Axual/axual/latest/docs/guides/connector-application I was able to create->delete->create->update
