### ISSUE TITLE
Best practice on managing app principals with TerraForm.

### ISSUE THREAD

**Issue by caspereijkens** [Axual/terraform-provider-axual#32]
The app principal resource uses a local file, which implies having all secrets locally when terraform runs. That seems quite insecure to us. What method do you propose to securely manage app principals with TerraForm?

**Comment by DarioAxual** [comment]
Hello @caspereijkens,

We have looked at the option given by Terraform and we propose to use the HashiCorp Vault to store securely the app principals.

Here is a link to configure Terraform to pull content from Vault - https://blog.gitguardian.com/how-to-handle-secrets-in-terraform/

**Comment by kasparAxual** [comment]
If there are any other questions regarding managing app principals with TerraForm, please let us know or open a new issue. Closing this issue.
