### ISSUE TITLE
Add support for Axual environment resource

### ISSUE THREAD

**Issue by caspereijkens** [Axual/terraform-provider-axual#5]
We would like to manage Axual environments with TerraForm since it is nicer to retrieve the environment ID from a TF resource rather than hardcoding it in the configuration.

**Comment by markaxual** [comment]
This shall be resolved in this MR. https://github.com/Axual/terraform-provider-axual/pull/9

**Comment by kasparAxual** [comment]
Fixed with: https://github.com/Axual/terraform-provider-axual/pull/7
